defaults:
  crypto_envelope: acrablock

schemas:
- table: "blog_entries"
  columns:
    - id
    - headline
    - slug
    - is_active
    - pub_date
    - content_format
    - summary
    - summary_html
    - body
    - body_html
    - author
  encrypted:
  - column: "author"
    data_type: "str"
    default_data_value: "error"
  - column: "body"
    data_type: "str"
    default_data_value: "error"
  - column: "body_html"
    data_type: "str"
    default_data_value: "error"
  - column: "headline"
    data_type: "str"
    default_data_value: "error"
  - column: "summary"
    data_type: "str"
    default_data_value: "error"
  - column: "summary_html"
    data_type: "str"
    default_data_value: "error"

- table: "dashboard_category"
  columns:
    - id
    - name
    - position
  encrypted:
    - column: "position"
      data_type: "int32"
      default_data_value: 0
