defaults:
  crypto_envelope: acrablock

schemas:
- table: "blog_entries"
  encrypted:
  - column: "author"
  - column: "body"
  - column: "body_html"
  - column: "headline"
  - column: "summary"
  - column: "summary_html"
