defaults:
  crypto_envelope: acrablock

schemas:
  - table: cpu_temp
    columns:
      - ts
      - device
      - unit_id
      - temp

    encrypted:
      - column: device
        data_type: str

      - column: unit_id
        data_type: str
