version: "3"

volumes:
  acra-translator:
  mongodb-data:
    driver: local

services:
  # Creating keys:
  # - ./.acrakeys/acra-translator/${ACRA_CLIENT_ID}_storage
  # - ./.acrakeys/acra-writer/${ACRA_CLIENT_ID}_storage.pub
  acra-keymaker_client:
    image: "cossacklabs/acra-keymaker:${ACRA_DOCKER_IMAGE_TAG:-0.95.0}"
    network_mode: "none"
    environment:
      ACRA_MASTER_KEY: ${ACRA_SERVER_MASTER_KEY:-N0MyZEVCRGY1cHA4ODRSVHp3c3BNeGtDekxaV3BhTHI=}
    volumes:
      - acra-translator:/keys
      - ../_common/ssl/acra-client/:/ssl:ro
    command: >-
      --client_id=""
      --tls_cert=/ssl/acra-client.crt
      --keys_output_dir=/keys/acra-translator
      --keys_public_output_dir=/keys/acra-translator
      --keystore=v1

  mongo:
    image: mongo:7.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - "27017:27017"
    networks:
      - go-mongo
      - world
      - webui-mongo

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER:-root}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN:-test}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD:-test}
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    networks:
      - world
      - webui-mongo

  acra-translator:
    image: "cossacklabs/acra-translator:${ACRA_DOCKER_IMAGE_TAG:-0.95.0}"
    # Restart server after correct termination, for example after the config
    # was changed through the API
    restart: always
    depends_on:
      - acra-keymaker_client
    environment:
      ACRA_MASTER_KEY: ${ACRA_SERVER_MASTER_KEY:-N0MyZEVCRGY1cHA4ODRSVHp3c3BNeGtDekxaV3BhTHI=}
    networks:
      - go-translator
    volumes:
      # Mount the directory with only the keys for this service. Must be
      # rewriteable in case of using API, otherwise should be read-only.
      #- keystore/acra-translator:/keys
      - acra-translator:/data
      - ../_common/ssl/acra-translator/:/ssl
      - ../_common/ssl/ca/ca.crt:/ssl/root.crt
    command: >-
      --incoming_connection_http_string=tcp://0.0.0.0:9595
      --keys_dir=/data/acra-translator
      --tls_ca=/ssl/root.crt
      --tls_cert=/ssl/acra-translator.crt
      --tls_key=/ssl/acra-translator.key
      --tls_ocsp_from_cert=ignore
      --tls_crl_from_cert=ignore
      --tls_auth=4      
      --d
      --v

  go-api-server:
    depends_on:
      - healthcheck-wait
      - acra-translator
    build:
      context: ./go-translator-demo
      dockerfile: ./docker/go-translator-demo.Dockerfile
      args:
        VCS_URL: ${COSSACKLABS_GO_TRANSLATOR_DEMO_VCS_URL}
        VCS_REF: ${COSSACKLABS_GO_TRANSLATOR_DEMO_VCS_REF}
        VCS_BRANCH: ${COSSACKLABS_GO_TRANSLATOR_DEMO_VCS_BRANCH}
        BUILD_DATE: ${COSSACKLABS_ACRAENGDEMO_BUILD_DATE}
    environment:
      ADDRESS: 0.0.0.0:8008
      SWAGGER_HOST: localhost:8008
      LOG_LEVEL: debug
      MONGODB_CONNECTION_URL: mongodb://root:password@mongo:27017/admin?authSource=admin
      ACRA_TRANSLATOR_URL: https://acra-translator:9595
      TLS_CLIENT_CERT_PATH: /ssl/acra-client.crt
      TLS_CLIENT_KEY_PATH: /ssl/acra-client.key
      TLS_CLIENT_CA_PATH: /ssl/root.crt
    volumes:
      - ../_common/ssl/acra-client/:/ssl
    ports:
      - "8008:8008"
    networks:
      - go-translator
      - go-mongo
      - world


  healthcheck-wait:
    image: busybox
    container_name: healthcheck-wait
    depends_on:
      mongo:
        condition: service_healthy

networks:
  world:
  go-translator:
    internal: true
  go-mongo:
    internal: true
  webui-mongo:
    internal: true
